### ISSUE TITLE
Running Sunflower from "develop" branch

### ISSUE THREAD

**Issue by reagentoo** [MeanEYE/Sunflower#369]
I'm trying to make package with new Sunflower using python 3.6, gtk+3 in Gentoo.
I see that setup.py file is missing in the project repository. Moreover, Sunflower.py file is also missing now. I'm not fully understand how current project should be structured in /usr/lib64/python3.6/site-packages/sunflower folder. Currently I have next failure:
```
$ python3.6 /usr/lib64/python3.6/site-packages/sunflower
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.6/site-packages/sunflower/__main__.py", line 53, in <module>
    from sunflower.gui.main_window import MainWindow
  File "/usr/lib64/python3.6/site-packages/sunflower/gui/main_window.py", line 22, in <module>
    from sunflower.mounts import MountsManager
  File "/usr/lib64/python3.6/site-packages/sunflower/mounts.py", line 4, in <module>
    from sunflower.widgets.location_menu import Location, GenericHeader
  File "/usr/lib64/python3.6/site-packages/sunflower/widgets/location_menu.py", line 9, in <module>
    from sunflower.plugin_base.item_list import ItemList
  File "/usr/lib64/python3.6/site-packages/sunflower/plugin_base/item_list.py", line 9, in <module>
    from sunflower.plugin_base.provider import Mode as FileMode
  File "/usr/lib64/python3.6/site-packages/sunflower/plugin_base/provider.py", line 6, in <module>
    from sunflower.plugin_base.monitor import Monitor
  File "/usr/lib64/python3.6/site-packages/sunflower/plugin_base/monitor.py", line 4, in <module>
    from queue import Queue, Empty as QueueEmptyException
  File "/usr/lib64/python3.6/site-packages/sunflower/queue.py", line 5, in <module>
    from queue import Queue, Empty
ImportError: cannot import name 'Queue'
```

**Comment by insolor** [comment]
Try to run as this:
```
python3.6 -m sunflower
```
(I suppose you've installed sunflower as a package)

**Comment by reagentoo** [comment]
@insolor thanks! It helps. Although I'm not sure that my package installs files properly:
https://gist.github.com/reagentoo/b7c7f14df91454cb950a604962a14c9a

**Comment by reagentoo** [comment]
Currently I have a problem with Sunflower's images dir.
I've added "images" into the /usr/lib64/python3.6/site-packages/sunflower.
A have next file structure:
```
$ ls -1 /usr/lib64/python3.6/site-packages/sunflower
accelerator_group.py
accelerator_manager.py
associations.py
common.py
config.py
emblems.py
gui
history.py
icons.py
images
indicator.py
__init__.py
keyring.py
__main__.py
menus.py
mounts.py
notifications.py
operation.py
parameters.py
plugin_base
plugins
__pycache__
queue.py
styles
toolbar.py
tools
widgets
```

Running script:
```
$ cat /usr/lib/python-exec/python3.6/sunflower
#!/usr/bin/env python3.6

import runpy
runpy.run_module('sunflower', run_name='__main__', alter_sys=True)
```

And I don't see any resources from "images" in the Sunflower. (app icon, about window picture, etc)
@MeanEYE please advice.

**Comment by MeanEYE** [comment]
Okay, so making packages for 0.4 is not currently working since we upgraded from GTK2 to 3, and from Python 2 to 3. So too many changes to keep up with package structure. Like @insolor stated you start it as a module now.

Sunflower will look for images in two places. Its local `images` directory and global storage for icons. However base path for images is determined relative to the operating directory of the application. If you run it just by `python3 -m sunflower`, even though module is available globally, it will most likely look for images in the wrong place. Try `cd`-ing into `/usr/lib/python-exec/python3.6/` and then executing the same command.

**Comment by reagentoo** [comment]
Unfortunately, cd into `/usr/lib/python-exec/python3.6/` does not affect anything.
I made one change to /usr/lib64/python3.6/site-packages/sunflower/gui/about_window.py:
```
# set about dialog image
- base_path = os.path.dirname(os.path.dirname(os.path.abspath(sys.argv[0])))
+ base_path = os.path.dirname(os.path.abspath(sys.argv[0]))
```
And now I've gotten `splash.png` in the About window.
But I still can not get the icon on the taskbar.

Updated ebuild: https://github.com/reagentoo/gentoo-overlay/blob/master/x11-misc/sunflower/sunflower-9999.ebuild

**Comment by MeanEYE** [comment]
Icons in the taskbar are no longer taken from the Window itself but rather `.desktop` file. So you'd have to have `sunflofer.png` in `/usr/share/icons` for it to load properly.

**Comment by reagentoo** [comment]
I have a pic for desktop icon, but still without taskbar pic.
```
/usr/share/applications/sunflower.desktop
/usr/share/icons/hicolor/64x64/apps/sunflower.png
/usr/share/icons/hicolor/scalable/apps/sunflower.svg
```

Also tried to change base_path in (but without any result)
```
sunflower/icons.py
sunflower/indicator.py
sunflower/notifications.py
```

**Comment by MeanEYE** [comment]
Can you please provide more information about which taskbar? Or even a screen shot. Am not sure which desktop environment you are using and that can play a role in correctly displaying icon.

**Comment by reagentoo** [comment]
@MeanEYE https://i.imgur.com/OtTEEdv.png

**Comment by MeanEYE** [comment]
What's the title for this entry on the taskbar? Is it `__main__`?

**Comment by reagentoo** [comment]
Title of this entry "Sunflower".

**Comment by MeanEYE** [comment]
Hm. I will have to figure out how to set this properly. Like I said, at some point they decided not to read icon from the window itself but rather from `.desktop` file which for some reason doesn't work all that well with Sunflower. Perhaps the difference is in the fact we are running the software as python3 module, so system attributes icon to python3 instead of program itself.

**Comment by reagentoo** [comment]
I'm not sure that `.desktop` is relevant here. We can run "sunflower" from console and the picmap on the taskbar should be. Also for example if I run "transmission" from console then I see transmission pic.

**Comment by MeanEYE** [comment]
Try opening `gnome-system-monitor` and see which icon is being used for Sunflower. If you are not using that system monitor, then whatever else.

**Comment by reagentoo** [comment]
I have `python3.6` process name in `gnome-system-monitor` without pixmap. Also as I said above I'm using this run script https://github.com/reagentoo/gentoo-overlay/blob/master/x11-misc/sunflower/files/sunflower

**Comment by MeanEYE** [comment]
Try making `.desktop` file and having it point `Exec` to your file. Icon should point to icon inside of our repo. It should work like that.

**Comment by reagentoo** [comment]
Please approve that you have pixmap of the running app. (Not just icon of the desktop shortcut on the workspace or panel)

**Comment by MeanEYE** [comment]
Sadly I don't have this issue solved yet. Everything I've said is a speculation which I need to test. I will find time to solve this issue this weekend. Approach you are going with by having simple Py script loading and executing module is a good one I feel, so I'll probably do that and update desktop file to test with.

**Comment by MeanEYE** [comment]
Okay, I have updated build scripts, tried all kinds of combinations with packages, modifications to .desktop file and I still can't resolve loading icon in the taskbar nor setting the application name, even though I am calling all the methods. 

I will have to dig deeper, but right now it's a mystery why this doesn't work.

**Comment by MeanEYE** [comment]
Okay, managed to solve it through very vaguely defined `set_prgname` in GLib. I have pushed changes to the repository. If you can, please test and let me know what else remains to be done for this to work for you.

**Comment by reagentoo** [comment]
@MeanEYE Hi. I've run it by desktop icon and from console and it's shows pix properly. And I didn't make any changes in the package. Well done!

**Comment by MeanEYE** [comment]
Thanks. Can this issue be closed now?

**Comment by reagentoo** [comment]
Yes.

**Comment by MeanEYE** [comment]
Great. Thanks for the help!
